#pragma once

#include <d3dx8.h>
#include "globals.h"
#include "drawing.h"
 
inline IDirect3DDevice8* Device{};
inline FenceCache fenceCache{};

namespace Log {
	inline auto PrintRenderState = [](D3DRENDERSTATETYPE State, const char* name) {
		DWORD value;
		if (!Device) return;
		Device->GetRenderState(State, &value);
		printf("%8x | %s\n", (unsigned int)value, name);
	};

	inline auto PrintRenderStates() {
		PrintRenderState(D3DRS_ZENABLE, "D3DRS_ZENABLE");
		PrintRenderState(D3DRS_FILLMODE, "D3DRS_FILLMODE");
		PrintRenderState(D3DRS_SHADEMODE, "D3DRS_SHADEMODE");
		PrintRenderState(D3DRS_LINEPATTERN, "D3DRS_LINEPATTERN");
		PrintRenderState(D3DRS_ZWRITEENABLE, "D3DRS_ZWRITEENABLE");
		PrintRenderState(D3DRS_ALPHATESTENABLE, "D3DRS_ALPHATESTENABLE");
		PrintRenderState(D3DRS_LASTPIXEL, "D3DRS_LASTPIXEL");
		PrintRenderState(D3DRS_SRCBLEND, "D3DRS_SRCBLEND");
		PrintRenderState(D3DRS_DESTBLEND, "D3DRS_DESTBLEND");
		PrintRenderState(D3DRS_CULLMODE, "D3DRS_CULLMODE");
		PrintRenderState(D3DRS_ZFUNC, "D3DRS_ZFUNC");
		PrintRenderState(D3DRS_ALPHAREF, "D3DRS_ALPHAREF");
		PrintRenderState(D3DRS_ALPHAFUNC, "D3DRS_ALPHAFUNC");
		PrintRenderState(D3DRS_DITHERENABLE, "D3DRS_DITHERENABLE");
		PrintRenderState(D3DRS_ALPHABLENDENABLE, "D3DRS_ALPHABLENDENABLE");
		PrintRenderState(D3DRS_FOGENABLE, "D3DRS_FOGENABLE");
		PrintRenderState(D3DRS_SPECULARENABLE, "D3DRS_SPECULARENABLE");
		PrintRenderState(D3DRS_ZVISIBLE, "D3DRS_ZVISIBLE");
		PrintRenderState(D3DRS_FOGCOLOR, "D3DRS_FOGCOLOR");
		PrintRenderState(D3DRS_FOGTABLEMODE, "D3DRS_FOGTABLEMODE");
		PrintRenderState(D3DRS_FOGSTART, "D3DRS_FOGSTART");
		PrintRenderState(D3DRS_FOGEND, "D3DRS_FOGEND");
		PrintRenderState(D3DRS_FOGDENSITY, "D3DRS_FOGDENSITY");
		PrintRenderState(D3DRS_EDGEANTIALIAS, "D3DRS_EDGEANTIALIAS");
		PrintRenderState(D3DRS_ZBIAS, "D3DRS_ZBIAS");
		PrintRenderState(D3DRS_RANGEFOGENABLE, "D3DRS_RANGEFOGENABLE");
		PrintRenderState(D3DRS_STENCILENABLE, "D3DRS_STENCILENABLE");
		PrintRenderState(D3DRS_STENCILFAIL, "D3DRS_STENCILFAIL");
		PrintRenderState(D3DRS_STENCILZFAIL, "D3DRS_STENCILZFAIL");
		PrintRenderState(D3DRS_STENCILPASS, "D3DRS_STENCILPASS");
		PrintRenderState(D3DRS_STENCILFUNC, "D3DRS_STENCILFUNC");
		PrintRenderState(D3DRS_STENCILREF, "D3DRS_STENCILREF");
		PrintRenderState(D3DRS_STENCILMASK, "D3DRS_STENCILMASK");
		PrintRenderState(D3DRS_STENCILWRITEMASK, "D3DRS_STENCILWRITEMASK");
		PrintRenderState(D3DRS_TEXTUREFACTOR, "D3DRS_TEXTUREFACTOR");
		PrintRenderState(D3DRS_WRAP0, "D3DRS_WRAP0");
		PrintRenderState(D3DRS_WRAP1, "D3DRS_WRAP1");
		PrintRenderState(D3DRS_WRAP2, "D3DRS_WRAP2");
		PrintRenderState(D3DRS_WRAP3, "D3DRS_WRAP3");
		PrintRenderState(D3DRS_WRAP4, "D3DRS_WRAP4");
		PrintRenderState(D3DRS_WRAP5, "D3DRS_WRAP5");
		PrintRenderState(D3DRS_WRAP6, "D3DRS_WRAP6");
		PrintRenderState(D3DRS_WRAP7, "D3DRS_WRAP7");
		PrintRenderState(D3DRS_CLIPPING, "D3DRS_CLIPPING");
		PrintRenderState(D3DRS_LIGHTING, "D3DRS_LIGHTING");
		PrintRenderState(D3DRS_AMBIENT, "D3DRS_AMBIENT");
		PrintRenderState(D3DRS_FOGVERTEXMODE, "D3DRS_FOGVERTEXMODE");
		PrintRenderState(D3DRS_COLORVERTEX, "D3DRS_COLORVERTEX");
		PrintRenderState(D3DRS_LOCALVIEWER, "D3DRS_LOCALVIEWER");
		PrintRenderState(D3DRS_NORMALIZENORMALS, "D3DRS_NORMALIZENORMALS");
		PrintRenderState(D3DRS_DIFFUSEMATERIALSOURCE, "D3DRS_DIFFUSEMATERIALSOURCE");
		PrintRenderState(D3DRS_SPECULARMATERIALSOURCE, "D3DRS_SPECULARMATERIALSOURCE");
		PrintRenderState(D3DRS_AMBIENTMATERIALSOURCE, "D3DRS_AMBIENTMATERIALSOURCE");
		PrintRenderState(D3DRS_EMISSIVEMATERIALSOURCE, "D3DRS_EMISSIVEMATERIALSOURCE");
		PrintRenderState(D3DRS_VERTEXBLEND, "D3DRS_VERTEXBLEND");
		PrintRenderState(D3DRS_CLIPPLANEENABLE, "D3DRS_CLIPPLANEENABLE");
		PrintRenderState(D3DRS_SOFTWAREVERTEXPROCESSING, "D3DRS_SOFTWAREVERTEXPROCESSING");
		PrintRenderState(D3DRS_POINTSIZE, "D3DRS_POINTSIZE");
		PrintRenderState(D3DRS_POINTSIZE_MIN, "D3DRS_POINTSIZE_MIN");
		PrintRenderState(D3DRS_POINTSPRITEENABLE, "D3DRS_POINTSPRITEENABLE");
		PrintRenderState(D3DRS_POINTSCALEENABLE, "D3DRS_POINTSCALEENABLE");
		PrintRenderState(D3DRS_POINTSCALE_A, "D3DRS_POINTSCALE_A");
		PrintRenderState(D3DRS_POINTSCALE_B, "D3DRS_POINTSCALE_B");
		PrintRenderState(D3DRS_POINTSCALE_C, "D3DRS_POINTSCALE_C");
		PrintRenderState(D3DRS_MULTISAMPLEANTIALIAS, "D3DRS_MULTISAMPLEANTIALIAS");
		PrintRenderState(D3DRS_MULTISAMPLEMASK, "D3DRS_MULTISAMPLEMASK");
		PrintRenderState(D3DRS_PATCHEDGESTYLE, "D3DRS_PATCHEDGESTYLE");
		PrintRenderState(D3DRS_PATCHSEGMENTS, "D3DRS_PATCHSEGMENTS");
		PrintRenderState(D3DRS_DEBUGMONITORTOKEN, "D3DRS_DEBUGMONITORTOKEN");
		PrintRenderState(D3DRS_POINTSIZE_MAX, "D3DRS_POINTSIZE_MAX");
		PrintRenderState(D3DRS_INDEXEDVERTEXBLENDENABLE, "D3DRS_INDEXEDVERTEXBLENDENABLE");
		PrintRenderState(D3DRS_COLORWRITEENABLE, "D3DRS_COLORWRITEENABLE");
		PrintRenderState(D3DRS_TWEENFACTOR, "D3DRS_TWEENFACTOR");
		PrintRenderState(D3DRS_BLENDOP, "D3DRS_BLENDOP");
		SetConsoleCursorPosition(GetStdHandle(STD_OUTPUT_HANDLE), COORD{});
	}
}